#!/usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 7.0
#  in conjunction with Tcl version 8.6
#    Dec 29, 2021 09:42:27 AM MST  platform: Linux

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *


class Toplevel1(tk.Tk):
    def __init__(self, master):
        """This class configures and populates the masterlevel window.
        master is the masterlevel containing window."""
        _bgcolor = "#d9d9d9"  # X11 color: 'gray85'
        _fgcolor = "#000000"  # X11 color: 'black'
        _compcolor = "#d9d9d9"  # X11 color: 'gray85'
        _ana1color = "#d9d9d9"  # X11 color: 'gray85'
        _ana2color = "#ececec"  # Closest X11 color: 'gray92'

        ##     master.geometry("600x800")
        ##     master.minsize(1, 1)
        ##     master.maxsize(1905, 1050)
        ##     master.resizable(1,  1)
        ##     master.title("masterlevel 0")

        self.master = master
        self.selectedButton = tk.IntVar()

        self.Frame1 = tk.Frame(self.master)
        self.Frame1.place(relx=0.75, rely=0.022, relheight=0.922, relwidth=0.208)

        self.Frame1.configure(relief="groove")
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief="groove")
        self.Frame1.configure(cursor="fleur")

        self.Button1 = tk.Button(self.Frame1)
        self.Button1.place(relx=0.24, rely=0.108, height=33, width=73)
        self.Button1.configure(borderwidth="2")
        self.Button1.configure(compound="left")
        self.Button1.configure(text="""Button""")

        self.Button2 = tk.Button(self.Frame1)
        self.Button2.place(relx=0.24, rely=0.265, height=33, width=73)
        self.Button2.configure(borderwidth="2")
        self.Button2.configure(compound="left")
        self.Button2.configure(text="""Button""")

        self.Button3 = tk.Button(self.Frame1)
        self.Button3.place(relx=0.24, rely=0.386, height=33, width=73)
        self.Button3.configure(borderwidth="2")
        self.Button3.configure(compound="left")
        self.Button3.configure(text="""Button""")

        self.Button4 = tk.Button(self.Frame1)
        self.Button4.place(relx=0.24, rely=0.545, height=33, width=73)
        self.Button4.configure(borderwidth="2")
        self.Button4.configure(compound="left")
        self.Button4.configure(text="""Button""")

        self.Button5 = tk.Button(self.Frame1)
        self.Button5.place(relx=0.24, rely=0.728, height=33, width=73)
        self.Button5.configure(borderwidth="2")
        self.Button5.configure(compound="left")
        self.Button5.configure(text="""Button""")

        self.Button6 = tk.Button(self.Frame1)
        self.Button6.place(relx=0.24, rely=0.872, height=33, width=73)
        self.Button6.configure(borderwidth="2")
        self.Button6.configure(compound="left")
        self.Button6.configure(text="""Button""")

        self.Button13 = tk.Button(self.Frame1)
        self.Button13.place(relx=0.24, rely=0.634, height=33, width=73)
        self.Button13.configure(borderwidth="2")
        self.Button13.configure(compound="left")
        self.Button13.configure(text="""Button""")

        self.Button14 = tk.Button(self.Frame1)
        self.Button14.place(relx=0.24, rely=0.024, height=33, width=73)
        self.Button14.configure(borderwidth="2")
        self.Button14.configure(compound="left")
        self.Button14.configure(text="""Button""")

        self.Button15 = tk.Button(self.Frame1)
        self.Button15.place(relx=0.24, rely=0.193, height=33, width=73)
        self.Button15.configure(borderwidth="2")
        self.Button15.configure(compound="left")
        self.Button15.configure(text="""Button""")

        self.Button16 = tk.Button(self.Frame1)
        self.Button16.place(relx=0.24, rely=0.458, height=33, width=73)
        self.Button16.configure(borderwidth="2")
        self.Button16.configure(compound="left")
        self.Button16.configure(text="""Button""")

        self.Entry1 = tk.Entry(self.master)
        self.Entry1.place(relx=0.067, rely=0.133, height=23, relwidth=0.143)
        self.Entry1.configure(background="white")
        self.Entry1.configure(font="TkFixedFont")

        self.Entry2 = tk.Entry(self.master)
        self.Entry2.place(relx=0.367, rely=0.133, height=23, relwidth=0.143)
        self.Entry2.configure(background="white")
        self.Entry2.configure(font="TkFixedFont")

        self.Label1 = tk.Label(self.master)
        self.Label1.place(relx=0.083, rely=0.089, height=21, width=39)
        self.Label1.configure(anchor="w")
        self.Label1.configure(compound="left")
        self.Label1.configure(text="""Label""")

        self.Label2 = tk.Label(self.master)
        self.Label2.place(relx=0.4, rely=0.089, height=21, width=39)
        self.Label2.configure(anchor="w")
        self.Label2.configure(compound="left")
        self.Label2.configure(text="""Label""")

        self.Entry3 = tk.Entry(self.master)
        self.Entry3.place(relx=0.6, rely=0.133, height=23, relwidth=0.143)
        self.Entry3.configure(background="white")
        self.Entry3.configure(font="TkFixedFont")

        self.Label3 = tk.Label(self.master)
        self.Label3.place(relx=0.667, rely=0.089, height=21, width=39)
        self.Label3.configure(anchor="w")
        self.Label3.configure(compound="left")
        self.Label3.configure(text="""Label""")

        self.Spinbox1 = tk.Spinbox(self.master, from_=1.0, to=100.0)
        self.Spinbox1.place(relx=0.067, rely=0.2, relheight=0.051, relwidth=0.147)
        self.Spinbox1.configure(activebackground="#f9f9f9")
        self.Spinbox1.configure(background="white")
        self.Spinbox1.configure(font="TkDefaultFont")
        self.Spinbox1.configure(highlightbackground="black")
        self.Spinbox1.configure(selectbackground="blue")
        self.Spinbox1.configure(selectforeground="white")

        self.Spinbox2 = tk.Spinbox(self.master, from_=1.0, to=100.0)
        self.Spinbox2.place(relx=0.383, rely=0.2, relheight=0.051, relwidth=0.113)
        self.Spinbox2.configure(activebackground="#f9f9f9")
        self.Spinbox2.configure(background="white")
        self.Spinbox2.configure(font="TkDefaultFont")
        self.Spinbox2.configure(highlightbackground="black")
        self.Spinbox2.configure(selectbackground="blue")
        self.Spinbox2.configure(selectforeground="white")

        self.Radiobutton1 = tk.Radiobutton(self.master)
        self.Radiobutton1.place(relx=0.6, rely=0.289, relheight=0.051, relwidth=0.113)
        self.Radiobutton1.configure(anchor="w")
        self.Radiobutton1.configure(compound="left")
        self.Radiobutton1.configure(justify="left")
        self.Radiobutton1.configure(text="""Radio""")
        self.Radiobutton1.configure(variable=self.selectedButton)

        self.Radiobutton2 = tk.Radiobutton(self.master)
        self.Radiobutton2.place(relx=0.6, rely=0.356, relheight=0.051, relwidth=0.113)
        self.Radiobutton2.configure(anchor="w")
        self.Radiobutton2.configure(compound="left")
        self.Radiobutton2.configure(justify="left")
        self.Radiobutton2.configure(text="""Radio""")
        self.Radiobutton2.configure(variable=self.selectedButton)

        self.Radiobutton3 = tk.Radiobutton(self.master)
        self.Radiobutton3.place(relx=0.6, rely=0.422, relheight=0.051, relwidth=0.113)
        self.Radiobutton3.configure(anchor="w")
        self.Radiobutton3.configure(compound="left")
        self.Radiobutton3.configure(justify="left")
        self.Radiobutton3.configure(text="""Radio""")
        self.Radiobutton3.configure(variable=self.selectedButton)

        self.Radiobutton4 = tk.Radiobutton(self.master)
        self.Radiobutton4.place(relx=0.6, rely=0.489, relheight=0.051, relwidth=0.113)
        self.Radiobutton4.configure(anchor="w")
        self.Radiobutton4.configure(compound="left")
        self.Radiobutton4.configure(justify="left")
        self.Radiobutton4.configure(text="""Radio""")
        self.Radiobutton4.configure(variable=self.selectedButton)

        self.Button7 = tk.Button(self.master)
        self.Button7.place(relx=0.083, rely=0.289, height=33, width=73)
        self.Button7.configure(borderwidth="2")
        self.Button7.configure(compound="left")
        self.Button7.configure(text="""Button""")

        self.Button8 = tk.Button(self.master)
        self.Button8.place(relx=0.083, rely=0.4, height=33, width=73)
        self.Button8.configure(borderwidth="2")
        self.Button8.configure(compound="left")
        self.Button8.configure(text="""Button""")

        self.Button9 = tk.Button(self.master)
        self.Button9.place(relx=0.083, rely=0.511, height=33, width=73)
        self.Button9.configure(borderwidth="2")
        self.Button9.configure(compound="left")
        self.Button9.configure(text="""Button""")

        self.Button10 = tk.Button(self.master)
        self.Button10.place(relx=0.367, rely=0.289, height=33, width=73)
        self.Button10.configure(borderwidth="2")
        self.Button10.configure(compound="left")
        self.Button10.configure(text="""Button""")

        self.Button11 = tk.Button(self.master)
        self.Button11.place(relx=0.367, rely=0.378, height=33, width=73)
        self.Button11.configure(borderwidth="2")
        self.Button11.configure(compound="left")
        self.Button11.configure(text="""Button""")

        self.Button12 = tk.Button(self.master)
        self.Button12.place(relx=0.367, rely=0.489, height=33, width=73)
        self.Button12.configure(borderwidth="2")
        self.Button12.configure(compound="left")
        self.Button12.configure(text="""Button""")

        self.Listbox1 = tk.Listbox(self.master)
        self.Listbox1.place(relx=0.083, rely=0.622, relheight=0.169, relwidth=0.14)
        self.Listbox1.configure(background="white")
        self.Listbox1.configure(font="TkFixedFont")

        self.Listbox2 = tk.Listbox(self.master)
        self.Listbox2.place(relx=0.367, rely=0.6, relheight=0.169, relwidth=0.14)

        self.Listbox2.configure(background="white")
        self.Listbox2.configure(font="TkFixedFont")


class masterlevel2:
    def __init__(self, master=None):
        """This class configures and populates the masterlevel window.
        master is the masterlevel containing window."""
        _bgcolor = "#d9d9d9"  # X11 color: 'gray85'
        _fgcolor = "#000000"  # X11 color: 'black'
        _compcolor = "#d9d9d9"  # X11 color: 'gray85'
        _ana1color = "#d9d9d9"  # X11 color: 'gray85'
        _ana2color = "#ececec"  # Closest X11 color: 'gray92'

        master.geometry("600x450+539+723")
        master.minsize(1, 1)
        master.maxsize(1905, 1050)
        master.resizable(1, 1)
        master.title("masterlevel 1")

        self.master = master

        self.Text1 = tk.Text(self.master)
        self.Text1.place(relx=0.183, rely=0.067, relheight=0.898, relwidth=0.777)
        self.Text1.configure(background="white")
        self.Text1.configure(font="TkTextFont")
        self.Text1.configure(selectbackground="blue")
        self.Text1.configure(selectforeground="white")
        self.Text1.configure(wrap="word")


class masterlevel3:
    def __init__(self, master=None):
        """This class configures and populates the masterlevel window.
        master is the masterlevel containing window."""
        _bgcolor = "#d9d9d9"  # X11 color: 'gray85'
        _fgcolor = "#000000"  # X11 color: 'black'
        _compcolor = "#d9d9d9"  # X11 color: 'gray85'
        _ana1color = "#d9d9d9"  # X11 color: 'gray85'
        _ana2color = "#ececec"  # Closest X11 color: 'gray92'

        master.geometry("600x450+620+820")
        master.minsize(1, 1)
        master.maxsize(1905, 1050)
        master.resizable(1, 1)
        master.title("masterlevel 2")

        self.master = master

        self.Canvas1 = tk.Canvas(self.master)
        self.Canvas1.place(relx=0.05, rely=0.022, relheight=0.958, relwidth=0.935)
        self.Canvas1.configure(borderwidth="2")
        self.Canvas1.configure(relief="ridge")
        self.Canvas1.configure(selectbackground="blue")
        self.Canvas1.configure(selectforeground="white")


if __name__ == "__main__":
    t = Toplevel1()
    t.mainloop()
